// Tests for 2. Add Two Numbers
// https://leetcode.com/problems/add-two-numbers/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest addTwoNumbers.2026.08.12.test.js

import { runCases } from "./_harness.js";
import { addTwoNumbers } from "./addTwoNumbers.2026.08.12.js";

// The harness's buildList coerces flat-array *inputs* into ListNodes, but has
// no inverse for the *return* value, so we serialize it back to an array here
// before handing off to runCases's array-based comparison.
const listToArray = (node) => {
  const out = [];
  for (; node; node = node.next) out.push(node.val);
  return out;
};

runCases({
  fn: (l1, l2) => listToArray(addTwoNumbers(l1, l2)),
  fnName: "addTwoNumbers",
  paramTypes: ["ListNode", "ListNode"],

  // 'exact' | 'unordered' | 'unorderedDeep'
  // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
  // If a failure says the elements match but the order doesn't,
  // change this one word.
  compare: "exact",

  cases: [
    {
      args: [
        [2, 4, 3],
        [5, 6, 4],
      ],
      expected: [7, 0, 8],
    },
    { args: [[0], [0]], expected: [0] },
    { args: [[9, 9], [9]], expected: [8, 0, 1] },
    {
      args: [
        [9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9],
      ],
      expected: [8, 9, 9, 9, 0, 0, 0, 1],
    },
  ],
});
