// Tests for 257. Binary Tree Paths
// https://leetcode.com/problems/binary-tree-paths/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest binaryTreePaths.2025.02.09.test.js

import { runCases } from './_harness.js';
import { binaryTreePaths } from './binaryTreePaths.2025.02.09.js';

runCases({
    fn: binaryTreePaths,
    fnName: 'binaryTreePaths',
    paramTypes: ["TreeNode"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'unordered' because the statement says the answer may be in any order.
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'unordered',

    cases: [
        { args: [[1, 2, 3, null, 5]], expected: ["1->2->5", "1->3"] },
        { args: [[1]], expected: ["1"] },
    ],
});
