// Tests for 464. Can I Win
// https://leetcode.com/problems/can-i-win/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest canIWin.2026.08.11.test.js

import { runCases } from './_harness.js';
import { canIWin } from './canIWin.2026.08.11.js';

runCases({
    fn: canIWin,
    fnName: 'canIWin',
    paramTypes: ["integer", "integer"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    cases: [
        { args: [10, 11], expected: false },
        { args: [10, 0], expected: true },
        { args: [10, 1], expected: true },
    ],
});
