// Tests for 162. Find Peak Element
// https://leetcode.com/problems/find-peak-element/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest findPeakElement.2025.02.11.test.js

import { runCases } from './_harness.js';
import { findPeakElement } from './findPeakElement.2025.02.11.js';

runCases({
    fn: findPeakElement,
    fnName: 'findPeakElement',
    paramTypes: ["integer[]"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',
    
    passWithNoTests: true,
    cases: [
        // { args: [[1, 2, 3, 1]], expected: 2 },
        // { args: [[1,2,1,3,5,6,4]], expected: 5 },
    ],
});
