// Tests for 14. Longest Common Prefix
// https://leetcode.com/problems/longest-common-prefix/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest longestCommonPrefix.2025.02.09.test.js

import { runCases } from './_harness.js';
import { longestCommonPrefix } from './longestCommonPrefix.2025.02.09.js';

runCases({
    fn: longestCommonPrefix,
    fnName: 'longestCommonPrefix',
    paramTypes: ["string[]"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    cases: [
        { args: [["flower", "flow", "flight"]], expected: "fl" },
        { args: [["dog", "racecar", "car"]], expected: "" },
    ],
});
