// Tests for 169. Majority Element
// https://leetcode.com/problems/majority-element/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest majorityElement.2025.02.09.test.js

import { runCases } from './_harness.js';
import { majorityElement } from './majorityElement.2025.02.09.js';

runCases({
    fn: majorityElement,
    fnName: 'majorityElement',
    paramTypes: ["integer[]"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    cases: [
        { args: [[3, 2, 3]], expected: 3 },
        { args: [[2, 2, 1, 1, 1, 2, 2]], expected: 2 },
    ],
});
