// Tests for 2623. Memoize
// https://leetcode.com/problems/memoize/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest memoize.2025.02.09.test.js

import { runCases } from './_harness.js';
import { foobar } from './memoize.2025.02.09.js';

runCases({
    fn: foobar,
    fnName: 'foobar',
    paramTypes: ["string", "string[]", "integer[][]"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    passWithNoTests: true,
    cases: [
        // { args: ["sum", ["call", "call", "getCallCount", "call", "getCallCount"], [[2, 2], [2, 2], [], [1, 2], []]], expected: [4, 4, 1, 3, 2] },
        // { args: ["factorial", ["call", "call", "call", "getCallCount", "call", "getCallCount"], [[2], [3], [2], [], [3], []]], expected: [2, 6, 2, 2, 6, 2] },
        // { args: ["fib", ["call", "getCallCount"], [[5], []]], expected: [8, 1] },
    ],
});
