// Tests for 66. Plus One
// https://leetcode.com/problems/plus-one/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest plusOne.2026.08.12.test.js

import { runCases } from "./_harness.js";
import { plusOne } from "./plusOne.2026.08.12.js";

runCases({
  fn: plusOne,
  fnName: "plusOne",
  paramTypes: ["integer[]"],

  // 'exact' | 'unordered' | 'unorderedDeep'
  // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
  // If a failure says the elements match but the order doesn't,
  // change this one word.
  compare: "exact",

  cases: [
    { args: [[1, 2, 3]], expected: [1, 2, 4] },
    { args: [[4, 3, 2, 1]], expected: [4, 3, 2, 2] },
    { args: [[9]], expected: [1, 0] },
    { args: [[9, 9, 9]], expected: [1, 0, 0, 0] },
    { args: [[1, 2, 9]], expected: [1, 3, 0] },
  ],
});
