// Tests for 383. Ransom Note
// https://leetcode.com/problems/ransom-note/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest ransomNote.2025.02.15.test.js

import { runCases } from './_harness.js';
import { canConstruct } from './ransomNote.2025.02.15.js';

runCases({
    fn: canConstruct,
    fnName: 'canConstruct',
    paramTypes: ["string", "string"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    cases: [
        { args: ["a", "b"], expected: false },
        { args: ["aa", "ab"], expected: false },
        { args: ["aa", "aab"], expected: true },
    ],
});
