// Tests for 189. Rotate Array
// https://leetcode.com/problems/rotate-array/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest rotateArray.2025.02.09.test.js

import { runCases } from './_harness.js';
import { rotate } from './rotateArray.2025.02.09.js';

runCases({
    fn: rotate,
    fnName: 'rotate',
    paramTypes: ["integer[]", "integer"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    // metaData.output: the answer is a mutated argument, not the
    // return value. Asserting on 'nums'.
    output: {"paramindex": 0},

    cases: [
        { args: [[1, 2, 3, 4, 5, 6, 7], 3], expected: [5, 6, 7, 1, 2, 3, 4] },
        { args: [[-1, -100, 3, 99], 2], expected: [3, 99, -1, -100] },
    ],
});
