// Tests for 35. Search Insert Position
// https://leetcode.com/problems/search-insert-position/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest searchInsertPosition.2026.07.28.test.js

import { runCases } from './_harness.js';
import { searchInsert } from './searchInsertPosition.2026.07.28.js';

runCases({
    fn: searchInsert,
    fnName: 'searchInsert',
    paramTypes: ["integer[]", "integer"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    passWithNoTests: true,
    cases: [
        // { args: [[1, 3, 5, 6], 5], expected: 2 },
        // { args: [[1, 3, 5, 6], 2], expected: 1 },
        // { args: [[1, 3, 5, 6], 7], expected: 4 },
    ],
});
