// Tests for 54. Spiral Matrix
// https://leetcode.com/problems/spiral-matrix/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest spiralMatrix.2026.08.12.test.js

import { runCases } from "./_harness.js";
import { spiralOrder } from "./spiralMatrix.2026.08.12.js";

runCases({
  fn: spiralOrder,
  fnName: "spiralOrder",
  paramTypes: ["integer[][]"],

  // 'exact' | 'unordered' | 'unorderedDeep'
  // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
  // If a failure says the elements match but the order doesn't,
  // change this one word.
  compare: "exact",

  cases: [
    {
      args: [
        [
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
        ],
      ],
      expected: [1, 2, 3, 6, 9, 8, 7, 4, 5],
    },
    {
      args: [
        [
          [1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
        ],
      ],
      expected: [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7],
    },
    { args: [[[7], [9], [6]]], expected: [7, 9, 6] },
    { args: [[[7]]], expected: [7] },
  ],
});
