// Tests for 20. Valid Parentheses
// https://leetcode.com/problems/valid-parentheses/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  node --test --watch leetcode/validParentheses.2026.08.11.test.js

const { runCases } = require("./_harness.js");

runCases({
  file: "validParentheses.2026.08.11.js",
  fnName: "isValid",
  paramTypes: ["string"],

  // 'exact' | 'unordered' | 'unorderedDeep'
  // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
  // If a failure says the elements match but the order doesn't,
  // change this one word.
  compare: "exact",

  cases: [
    { args: ["()"], expected: true },
    { args: ["()[]{}"], expected: true },
    { args: ["(]"], expected: false },
    { args: ["([])"], expected: true },
    { args: ["([)]"], expected: false },
    { args: ["[[[]"], expected: false },
    { args: ["(([]){})"], expected: true },
  ],
});
