// Tests for 242. Valid Anagram
// https://leetcode.com/problems/valid-anagram/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  node --test --watch leetcode/validAnagram.2026.08.09.test.js

const { runCases } = require('./_harness.js');

runCases({
    file: 'validAnagram.2026.08.09.js',
    fnName: 'isAnagram',
    paramTypes: ["string", "string"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    cases: [
        { args: ["anagram", "nagaram"], expected: true },
        { args: ["rat", "car"], expected: false },
    ],
});
