// Tests for 20. Valid Parentheses
// https://leetcode.com/problems/valid-parentheses/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest validParentheses.2026.08.11.test.js

import { runCases } from './_harness.js';
import { isValid } from './validParentheses.2026.08.11.js';

runCases({
  fn: isValid,
  fnName: "isValid",
  paramTypes: ["string"],

  // 'exact' | 'unordered' | 'unorderedDeep'
  // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
  // If a failure says the elements match but the order doesn't,
  // change this one word.
  compare: "exact",

  cases: [
    { args: ["()"], expected: true },
    { args: ["()[]{}"], expected: true },
    { args: ["(]"], expected: false },
    { args: ["([])"], expected: true },
    { args: ["([)]"], expected: false },
    { args: ["[[[]"], expected: false },
    { args: ["[[]"], expected: false },
    { args: ["(([]){})"], expected: true },
    { args: ["}}"], expected: false },
  ],
});
