// Tests for 125. Valid Palindrome
// https://leetcode.com/problems/valid-palindrome/
// Generated by tools/fetch_problem.py — edit freely.
//
// Run:  npx vitest validPalindrome.2025.02.14.test.js

import { runCases } from './_harness.js';
import { isPalindrome } from './validPalindrome.2025.02.14.js';

runCases({
    fn: isPalindrome,
    fnName: 'isPalindrome',
    paramTypes: ["string"],

    // 'exact' | 'unordered' | 'unorderedDeep'
    // Chose 'exact' because no order flag in metaData and the statement doesn't say "any order".
    // If a failure says the elements match but the order doesn't,
    // change this one word.
    compare: 'exact',

    cases: [
        { args: ["A man, a plan, a canal: Panama"], expected: true },
        { args: ["race a car"], expected: false },
        { args: [" "], expected: true },
    ],
});
